### ISSUE TITLE
 can not scroll the view in MarkDown file

### ISSUE THREAD

**Issue by firsthubgit** [CodeHubApp/CodeHub#651] opened 2020-01-18 17:05 UTC
I cant scroll the view in the  markdown file

**Comment by DavidHaslam** [comment] 2020-01-18 17:18
Duplicate of #613

**Comment by cadkins052** [comment] 2020-01-19 07:08
Scenario!:)

**Comment by DavidHaslam** [comment] 2020-05-14 05:54
Fixed in new release.

**Closed** 2020-05-14 15:43 UTC
