### ISSUE TITLE
iPhone SE iOS 13 not scrolling 

### ISSUE THREAD

**Issue by feilipu** [CodeHubApp/CodeHub#658] opened 2020-03-11 03:04 UTC
No scrolling on readme or on code. This is a regression.

**Comment by garrettw** [comment] 2020-03-11 14:48
Duplicate of #613

**Comment by guoruibiao** [comment] 2020-03-18 01:16
so many duplicated issues.

**Comment by Rexogamer** [comment] 2020-03-18 07:34
This app hasn’t really been worked on much lately. If anyone has made an active fork lmk

**Comment by chris18890** [comment] 2020-03-18 14:06
Dunno how useful/relevant this is - https://www.itpro.co.uk/software/development/355030/github-releases-mobile-app-for-ios-and-android

**Comment by Rexogamer** [comment] 2020-03-18 18:00
The official github app is nice but doesn’t have editing support so :/

**Comment by feilipu** [comment] 2020-03-18 19:55
Closing this. Moving to another application.

Thanks for the initial work.

**Closed** 2020-03-18 20:00 UTC
