### ISSUE TITLE
Image not opening in readme.md

### ISSUE THREAD

**Issue by LeWarEnds** [CodeHubApp/CodeHub#560] opened 2019-02-05 16:17 UTC
When I try to open the image in a readme, it does not open.

**Comment by garrettw** [comment] 2019-02-05 16:31
Duplicate of #461 - please close

**Comment by LeWarEnds** [comment] 2019-02-05 16:59
Ill close it and do take a look at issue#554

**Closed** 2019-02-05 17:18 UTC

**Comment by MYCampanula** [comment] 2019-02-05 19:34
G00D

**Comment by MYCampanula** [comment] 2019-02-07 08:35
TEM00@findmima.com
