### ISSUE TITLE
Readme.md problems

### ISSUE THREAD

**Issue by tomasovic** [CodeHubApp/CodeHub#641] opened 2019-12-08 22:09 UTC
There is a problem with scrolling readme.md files.

**Comment by garrettw** [comment] 2019-12-09 14:50
Duplicate of #613

**Closed** 2019-12-09 19:25 UTC

**Comment by AlbertWinestien** [comment] 2019-12-10 00:45
Relaying ongoing issue with readme scroll issue

**Comment by wuxiaolee** [comment] 2019-12-10 00:54
Get it！Thanks！





------------------ Original ------------------
