### ISSUE TITLE
‘Forked from’ crashing the app

### ISSUE THREAD

**Issue by charlesrocket** [CodeHubApp/CodeHub#416] opened 2018-01-01 23:02 UTC
The app is exiting with error after ‘Forked from’ action called. Same error if called from different directories. 

current build, lates iOS (11.2.1) on 6s

**Comment by thedillonb** [comment] 2018-01-01 23:29
Darn, I knew I'd shoot myself in the foot closing #415 before the version was actually released... I've fixed this bad Larry and have submitted the fix to Apple, it's in review right now. Usually I close the issues when the version is released but I accidentally closed it prematurely. This is a dupe of #415 but I'll leave it open for anyone else who swings by.

**Comment by charlesrocket** [comment] 2018-01-01 23:43
got it )

**Comment by ovo1381** [comment] 2018-01-02 03:15
how to ignore this email??? i dont want to recieve this alert plz help

—
즐거운 MailTime (http://mailti.me/m|9) 되세요

**Comment by psipika** [comment] 2018-01-02 03:21
The email you received has links at the bottom.
You can disable all by clicking on "Unwatch" at the top right of the main page of this repo.

**Comment by jessegadgets** [comment] 2018-01-02 05:12
click on mute thred below
 

Sent: Monday, January 01, 2018 at 10:16 PM

**Comment by thedillonb** [comment] 2018-01-03 05:03
Ok, this is actually fixed now. A new version was released to the app store earlier today that resolves this issue.

**Closed by thedillonb** 2018-01-03 05:03 UTC
