### ISSUE TITLE
Unable to add a comment to a commit

### ISSUE THREAD

**Issue by DavidHaslam** [CodeHubApp/CodeHub#571] opened 2019-03-10 10:21 UTC
I just tried adding a comment to a commit and got refused. 

![Image](https://i.imgur.com/uOoNnqn.jpg)

Aside: I have editor rights to the repository even though I’m not the owner.

**Comment by garrettw** [comment] 2019-03-10 23:15
Duplicate of #289

**Comment by thedillonb** [comment] 2019-03-11 14:36
Will track via #289

**Closed by thedillonb** 2019-03-11 14:36 UTC
