### ISSUE TITLE
Add more git services 

### ISSUE THREAD

**Issue by rluvaton** [CodeHubApp/CodeHub#451] opened 2018-03-04 10:22 UTC
# Adding More Git Services

This app is awesome, but I feel like if more git services (Like GitLab) was here too it could be much greater!

**Comment by thedillonb** [comment] 2018-03-05 02:41
Marking as a duplicate of #268. Embedding GitLab functionally alongside GitHub's is a bit of a technical stretch, but forking the app for GitLab is feasible.

**Closed by thedillonb** 2018-03-05 02:41 UTC

**Comment by rluvaton** [comment] 2018-03-05 11:33
I will try to do it, if its the problem
