### ISSUE TITLE
Unable scroll while reading readme.md

### ISSUE THREAD

**Issue by themikesam** [CodeHubApp/CodeHub#636] opened 2019-11-14 03:51 UTC
As title.

**Comment by garrettw** [comment] 2019-11-14 15:26
Please check for existing issues that match your problem before posting a new one.

This is a duplicate of #632.

**Comment by azfarB** [comment] 2019-11-14 15:43
Hello Garett,

Not that I’m saying I haven’t made a problem but can you pls possibly send me a post of the problem in question?

Thanks,
Azfar

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by garrettw** [comment] 2019-11-14 15:55
@azfarB I was not addressing you at all. I was replying to someone else's issue report. If you want to stop receiving these notifications you need to unwatch the CodeHub repository, either through the app or on github.com .

**Comment by azfarB** [comment] 2019-11-15 05:46
Dear Garett,

I am sorry, I am new to this; so got a little confused. Pls do forgive me!

Best,
Azfar

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by thedillonb** [comment] 2019-11-29 02:30
Duplicate of #613.

**Closed** 2019-11-29 02:30 UTC
