### ISSUE TITLE
Script Reading Size.

### ISSUE THREAD

**Issue by LeWarEnds** [CodeHubApp/CodeHub#525] opened 2018-10-25 08:12 UTC
When we open a script file in the CodeHub, it is shown in desktop view  making it hard to read. As the size of text is small, this can be the improvment.

**Comment by garrettw** [comment] 2018-10-25 14:34
Duplicate of #520. As you have even commented on the original issue, please do not intentionally create duplicates.

**Comment by garrettw** [comment] 2018-10-26 16:11
I think you can only close the issue, not delete it.

**Closed** 2018-12-06 17:48 UTC
