### ISSUE TITLE
Can’t scroll readme.md files

### ISSUE THREAD

**Issue by aqm1152** [CodeHubApp/CodeHub#650] opened 2020-01-03 21:18 UTC
I am not able to scroll README.md files. I am not sure if this is for all text files since image files or pdfs seem fine.

**Comment by garrettw** [comment] 2020-01-03 21:27
Duplicate of #613

**Comment by Bleeck** [comment] 2020-01-04 09:13
Copy pasting comment from 613.


This seems to just be an input issue. I can't scroll by swiping but I did manage to get the page to scroll up or down by doing multiple taps at the bottom of the page or the top of the page respectively.

So just tap like crazy and it should move.

This workaround should keep us going until a proper fix is implemented.

**Comment by kaneci** [comment] 2020-01-15 03:42
Me too

**Comment by ck2000** [comment] 2020-01-26 21:17
Me too

**Comment by cadkins052** [comment] 2020-01-26 21:56
Scenario!:)

**Comment by cadkins052** [comment] 2020-01-27 04:50
Scenario!:)

**Comment by garrettw** [comment] 2020-01-27 14:59
Please stop and comment only on #613.

**Comment by DavidHaslam** [comment] 2020-05-14 05:55
Fixed in new release.

**Closed** 2020-05-14 15:44 UTC
