### ISSUE TITLE
GitLab Support 

### ISSUE THREAD

**Issue by BaileyJM02** [CodeHubApp/CodeHub#481] opened 2018-06-03 10:18 UTC
I think it would be awesome to add some GitLab support to the app!

**Comment by garrettw** [comment] 2018-06-04 13:17
As per #179, due to technical differences between the platforms, it's not that simple to just "add support" for GitLab. So we'll call this a duplicate of #268.
In the future, please do a quick search of existing issues before creating a new one.

**Closed** 2019-10-06 02:42 UTC

**Comment by claudiodcrizzi** [comment] 2019-10-06 16:10
Mute the thread
-- 
Atenciosamente Claudio Donizeti Colsera Rizzi
Obrigado.
