### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by mikeerickson** [CodeHubApp/CodeHub#248] opened 2017-01-04 21:56 UTC
Any chance one of the contributors has worked on (or working on) a dark theme for CodeHub?

If not, would such a PR be acceptable?

**Comment by mikeerickson** [comment] 2017-02-12 19:38
🏓

**Comment by TheRealGus** [comment] 2017-02-12 19:40
wtf I didn't subscribe to this and even I after I muted this I'm still getting emails about it quite perplexing

**Comment by thedillonb** [comment] 2017-02-12 19:44
@TheRealGus Simply unwatch the repository. When you downloaded the app, during the walkthrough, you must have tapped "Watch" which would subscribe you for notifications.

**Comment by thedillonb** [comment] 2017-12-17 04:45
Consolidating issues. Dupe of #127

**Closed by thedillonb** 2017-12-17 04:45 UTC
