### ISSUE TITLE
Losing track of what repo a notification came from

### ISSUE THREAD

**Issue by stickystyle** [CodeHubApp/CodeHub#568] opened 2019-02-21 03:50 UTC
When we get a notification for a comment on an issue, we can see the repo it's from in the notification, however once we go into the issue there is nothing in the UI to indicate what repo we are in. 
The situation that happens frequently is I'm using my phone and a notification pops in, I just see is codehub so I know I want it and just tap it to jump in... before really reading it. Now I'm in the app and I can't figure out what project I'm reading about from a issue I subscribed to a year ago. 

So if you could include the repo somewhere in the UI when viewing an issue, that would be great :)

**Comment by garrettw** [comment] 2019-02-21 14:28
Duplicate of #564

**Comment by thedillonb** [comment] 2019-02-22 11:24
Closing as dupe.

**Closed by thedillonb** 2019-02-22 11:24 UTC
