### ISSUE TITLE
Unable to scroll Readme

### ISSUE THREAD

**Issue by muhdarifrawi** [CodeHubApp/CodeHub#632] opened 2019-10-18 15:26 UTC
I have to open up to github to read my readme. If it helps, i'm using iPhone 7 Plus and iOS 13.1.2. Thanks alot! I'm loving this app so far.

**Comment by mrMersinlioglu** [comment] 2019-10-18 16:01
Hello, Firstly click on the download to application Code. After open the readme in text


Sent from Yahoo Mail for iPhone


On Cuma, Ekim 18, 2019, 6:32 ÖS, Arif Rawi <notifications@github.com> wrote:


I have to open up to github to read my readme. If it helps, i'm using iPhone 7 Plus and iOS 13.1.2. Thanks alot! I'm loving this app so far.

**Comment by muhdarifrawi** [comment] 2019-10-19 00:20
Hi thank you for the help! Though I can't seem to find where to download the readme file to the CodeHub app. Could you guide me step-by-step. Thank you!

**Comment by foxip** [comment] 2019-10-28 19:26
Same problem here, scrolling does not work when opening the readme of a repo.

**Comment by foxip** [comment] 2019-10-28 19:28
Related to #613

**Comment by fasm** [comment] 2019-11-12 05:05
Same... This seems like a quite impactful problem to go unfixed for 2 months+

**Comment by jamesleesaunders** [comment] 2019-11-20 14:50
Same as #613 Is there any update on this? Unable to scroll markdown files.

**Comment by DavidHaslam** [comment] 2019-11-27 13:12
The issue affects all MarkDown files with extension .md

None of them vertically scroll anymore. 

Rather critical for any text project in which all the source files are MD.

**Comment by DavidHaslam** [comment] 2019-11-27 13:14
Duplicate of issue #613


Scrolling is unresponsive in .md files. 
Device: iPhone 7 iOS 12.4 https://github.com/CodeHubApp/CodeHub/issues/613

**Comment by wulinlin** [comment] 2019-12-04 23:34
ios13.3 the same problem

**Comment by iamgalaxy84** [comment] 2019-12-05 07:00
What problem

Sent from my Verizon, Samsung Galaxy smartphone
Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by garrettw** [comment] 2019-12-05 15:04
If you're not going to bother clicking the link in the email to the issue where the comment was posted, I'm not going to bother telling you "what problem".
If you don't want to receive these emails, you're free to unwatch this repo.

**Comment by tanekone** [comment] 2019-12-14 01:15
iPhone11 the same question，can`t scroll.

**Comment by josefglatz** [comment] 2020-03-11 04:00
Same problem on iPhone 8+

**Comment by bibstha** [comment] 2020-04-20 03:41
I've opened up a PR. This should fix the issue.

**Comment by DavidHaslam** [comment] 2020-05-14 05:56
Fixed.

**Closed** 2020-05-14 15:45 UTC
